version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  api:
    build: ./backend
    container_name: api
    ports:
      - "8000:8000"
    environment:
      USER: "root"
      PASS: "root"
      HOST: "192.168.57.128"
      PORT: 5432
      NAME: "mydatabase"
    depends_on:
      - postgres

